import { ArrowRight, HeartHandshake, MapPin, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import Header from '../components/Header.jsx'
import Map from '../components/Map.jsx'
import ReportCard from '../components/ReportCard.jsx'
import { REPORTS } from '../lib/constants.js'
export default function Home() {
 return <><Header /><main><section className="bg-gradient-to-br from-blue-50 via-white to-slate-50"><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-14 sm:px-6 md:grid-cols-2 md:py-20 lg:px-8"><div><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white px-3 py-1 text-sm font-semibold text-blue-800"><ShieldCheck size={16}/>Community-powered accessibility</span><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Move through your city with confidence.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Plan routes around your access needs and learn from people who know the places you are going.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/search" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700">Find an accessible route<ArrowRight size={18}/></Link><Link to="/report" className="inline-flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-800 hover:bg-slate-50">Share a report</Link></div></div><Map className="min-h-80 shadow-sm"/></div></section><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-800">From the community</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Recent accessibility updates</h2></div><Link to="/report" className="text-sm font-semibold text-blue-800 hover:underline">Add an update</Link></div><div className="mt-6 grid gap-4 md:grid-cols-3">{REPORTS.map(report => <ReportCard key={report.id} report={report} actionLabel="See details" />)}</div></section><section className="border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-12 sm:px-6 md:grid-cols-3 lg:px-8"><div><MapPin className="text-blue-700"/><h3 className="mt-3 font-bold">Plan around your needs</h3><p className="mt-2 text-sm leading-6 text-slate-600">Compare route options and accessibility details before you leave.</p></div><div><HeartHandshake className="text-blue-700"/><h3 className="mt-3 font-bold">Share what you know</h3><p className="mt-2 text-sm leading-6 text-slate-600">Your local knowledge helps neighbors make informed choices.</p></div><div><ShieldCheck className="text-blue-700"/><h3 className="mt-3 font-bold">Built for clarity</h3><p className="mt-2 text-sm leading-6 text-slate-600">Clear status labels make helpful details easy to scan.</p></div></div></section></main></>
}
