import { useState } from 'react'
import { CheckCircle2 } from 'lucide-react'
import Header from '../components/Header.jsx'
import ErrorToast from '../components/ErrorToast.jsx'
export default function ReportForm() {
 const [error, setError] = useState('')
 const [submitted, setSubmitted] = useState(false)
 function submit(event) { event.preventDefault(); const data = new FormData(event.currentTarget); if (!data.get('location') || !data.get('description')) { setError('Add a location and description to submit your report.'); return } setError(''); setSubmitted(true); event.currentTarget.reset() }
 return <><Header/><main className="mx-auto max-w-3xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-wide text-blue-800">Community reporting</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Share an accessibility update</h1><p className="mt-3 text-slate-600">A clear, respectful report helps someone decide what to expect before they arrive.</p>{submitted && <div role="status" className="mt-6 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><CheckCircle2 size={20}/>Thanks. Your demo report has been recorded on this page.</div>}<form onSubmit={submit} className="mt-7 grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><label className="grid gap-2 text-sm font-semibold">Issue type<select name="type" className="min-h-11 rounded-lg border border-slate-300 bg-white px-3 font-normal focus-visible:outline-2 focus-visible:outline-blue-700"><option>Access feature</option><option>Blocked curb ramp</option><option>Uneven sidewalk</option><option>Elevator or entrance</option><option>Other barrier</option></select></label><label className="grid gap-2 text-sm font-semibold">Location<input name="location" required placeholder="Place, address, or landmark" className="min-h-11 rounded-lg border border-slate-300 px-3 font-normal focus-visible:outline-2 focus-visible:outline-blue-700"/></label><label className="grid gap-2 text-sm font-semibold">What did you notice?<textarea name="description" required rows="5" placeholder="Describe the feature or barrier and where it is." className="rounded-lg border border-slate-300 px-3 py-2 font-normal focus-visible:outline-2 focus-visible:outline-blue-700"/></label><button className="min-h-12 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700">Submit report</button><p className="text-xs leading-5 text-slate-500">Demo only. Your report is not sent to a server.</p></form></main><ErrorToast message={error} onClose={() => setError('')}/></>
}
