import { useEffect, useMemo, useState } from "react";
import { Search, Users } from "lucide-react";
import Header from "../components/Header.jsx";
import ReportCard from "../components/ReportCard.jsx";
import LoadingSpinner from "../components/LoadingSpinner.jsx";
import ErrorToast from "../components/ErrorToast.jsx";
import { getPendingReports, getReports, verifyReport } from "../lib/api.js";
import { EmptyState } from "../lib/messages.jsx";
export default function VolunteerDashboard() {
 const [reports, setReports] = useState([]), [reviewable, setReviewable] = useState(() => new Set()), [loading, setLoading] = useState(true), [workingId, setWorkingId] = useState(null), [error, setError] = useState(""), [query, setQuery] = useState(""), [filter, setFilter] = useState("All");
 // Same list as the home page (all reports); the pending queue only decides which ones this volunteer can act on.
 const load = () => Promise.all([getReports(), getPendingReports()]);
 async function refresh() { const [all, queue] = await load(); setReports(all); setReviewable(new Set(queue.map(report => report.id))); }
 useEffect(() => { let live = true; load().then(([all, queue]) => { if (live) { setReports(all); setReviewable(new Set(queue.map(report => report.id))); } }).catch(err => { if (live) setError(err.message || "Reports could not be loaded."); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, []);
 const pending = reports.filter(report => report.status === "Pending" && reviewable.has(report.id)).length, verifiedCount = reports.filter(report => report.status === "Verified").length;
 const filtered = useMemo(() => reports.filter(report => (filter === "All" || report.status === filter) && (report.location + " " + report.issueType + " " + report.description).toLowerCase().includes(query.toLowerCase())), [reports, filter, query]);
 async function changeStatus(id, status) { setWorkingId(id); setError(""); try { await verifyReport(id, status); await refresh(); } catch (err) { setError(err.message || "The report could not be verified."); } finally { setWorkingId(null); } }
 return <><Header/><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-wide text-blue-800">Community response</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Volunteer dashboard</h1><p className="mt-2 text-slate-600">Review reports and keep accessibility information current.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Stat title="Pending review" count={pending} tone="amber"/><Stat title="Verified" count={verifiedCount} tone="green"/></div><section className="mt-9"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">Reports to review</h2><p className="mt-1 text-sm text-slate-600">{reports.length} reports from AccessiNav</p></div><Users className="text-blue-700" aria-hidden="true"/></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_220px]"><label className="relative block"><span className="sr-only">Search reports</span><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search location or issue" className="min-h-11 w-full rounded-xl border border-slate-300 pl-10 pr-3 focus-visible:outline-2 focus-visible:outline-blue-700"/></label><label className="sr-only" htmlFor="volunteer-status">Filter reports by status</label><select id="volunteer-status" value={filter} onChange={e => setFilter(e.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 focus-visible:outline-2 focus-visible:outline-blue-700"><option>All</option><option>Pending</option><option>Verified</option><option>Rejected</option></select></div><div className="mt-5">{loading ? <div className="rounded-xl border bg-white p-8"><LoadingSpinner label="Loading reports…"/></div> : filtered.length ? <div className="grid gap-4 lg:grid-cols-2">{filtered.map(report => <div key={report.id} className="relative"><ReportCard report={report} onVerify={report.status === "Pending" && reviewable.has(report.id) ? changeStatus : undefined}/>{report.status === "Pending" && !reviewable.has(report.id) && <p className="mt-2 px-1 text-xs text-slate-600">You submitted this report, so another volunteer or organization needs to verify it.</p>}{workingId === report.id && <div className="absolute inset-0 grid place-items-center rounded-2xl bg-white/70"><LoadingSpinner label="Updating…"/></div>}</div>)}</div> : <EmptyState title="No matching reports">Try changing the status filter or search term.</EmptyState>}</div></section></main><ErrorToast message={error} onClose={() => setError("")}/></>;
}
function Stat({ title, count, tone }) { const tones = { amber: "bg-amber-50 text-amber-950", blue: "bg-blue-50 text-blue-950", green: "bg-emerald-50 text-emerald-950" }; return <div className={"rounded-2xl border border-slate-200 p-5 " + tones[tone]}><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-3xl font-bold">{count}</p></div>; }
