import { Accessibility, LogOut, Menu, Settings, UserRound, X } from "lucide-react";
import { useState } from "react";
import { Link, NavLink, useNavigate } from "react-router-dom";
import { clearCurrentUser, getCurrentUser } from "../lib/auth.js";

const links = [{ to: "/home", label: "Home" }, { to: "/search", label: "Search" }, { to: "/report", label: "Report Issue" }];
export default function Header() {
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();
  const user = getCurrentUser();
  const classes = ({ isActive }) => "rounded-lg px-3 py-2 text-sm font-semibold hover:bg-blue-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700 " + (isActive ? "bg-blue-50 text-blue-800" : "text-slate-600");
  function logout() { clearCurrentUser(); setOpen(false); navigate("/", { replace: true }); }
  return <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8">
    <Link to={user ? "/home" : "/"} className="flex shrink-0 items-center gap-2 rounded-lg text-lg font-bold text-slate-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700"><span className="grid size-9 place-items-center rounded-xl bg-blue-700 text-white"><Accessibility size={21} aria-hidden="true"/></span>AccessiNav</Link>
    <nav aria-label="Main navigation" className="hidden items-center gap-1 sm:flex">{links.map(link => <NavLink key={link.to} to={link.to} className={classes}>{link.label}</NavLink>)}{user?.role === "volunteer" && <NavLink to="/volunteer" className={classes}>Volunteer</NavLink>}{user?.role === "ngo" && <NavLink to="/ngo" className={classes}>Organization</NavLink>}</nav>
    <div className="hidden items-center gap-3 sm:flex">{user ? <><NavLink to="/settings" className={classes}><span className="inline-flex items-center gap-2"><Settings size={17} aria-hidden="true"/>Accessibility</span></NavLink><span className="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><UserRound size={17}/>{user.name}</span><button type="button" onClick={logout} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-300 px-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-blue-700"><LogOut size={16}/>Log out</button></> : <Link to="/login" className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800">Log in</Link>}</div>
    <button type="button" className="grid size-10 place-items-center rounded-lg text-slate-700 hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-blue-700 sm:hidden" aria-label={open ? "Close navigation menu" : "Open navigation menu"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X size={22}/> : <Menu size={22}/>}</button>
  </div>{open && <div className="grid gap-2 border-t border-slate-200 px-4 py-3 sm:hidden"><nav aria-label="Mobile navigation" className="grid gap-1">{links.map(link => <NavLink key={link.to} to={link.to} onClick={() => setOpen(false)} className={classes}>{link.label}</NavLink>)}{user?.role === "volunteer" && <NavLink to="/volunteer" onClick={() => setOpen(false)} className={classes}>Volunteer dashboard</NavLink>}{user?.role === "ngo" && <NavLink to="/ngo" onClick={() => setOpen(false)} className={classes}>Organization dashboard</NavLink>}{user && <NavLink to="/settings" onClick={() => setOpen(false)} className={classes}>Accessibility settings</NavLink>}</nav>{user ? <div className="flex items-center justify-between border-t pt-3"><span className="text-sm font-medium text-slate-700">{user.name}</span><button type="button" onClick={logout} className="inline-flex min-h-10 items-center gap-2 rounded-lg border px-3 text-sm font-semibold"><LogOut size={16}/>Log out</button></div> : <Link onClick={() => setOpen(false)} to="/login" className="rounded-lg bg-blue-700 px-4 py-3 text-center font-semibold text-white">Log in</Link>}</div>}</header>;
}
